import { Agent } from "@real-estate/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@cresentsothebys.com",
    phone: "(504) 555-0192",
    officeState: "LA",
    serviceAreas: ["New Orleans", "Metairie", "Kenner", "Slidell"],
    facebookPageUrl: "https://facebook.com/sarahjenkinsrealty",
    instagramPageUrl: "https://instagram.com/sarahjenkinsnola",
    crossPostPreference: "all",
  },
  {
    id: "agent-2",
    name: "Marcus Vance",
    email: "marcus.vance@cresentsothebys.com",
    phone: "(228) 555-0143",
    officeState: "MS",
    serviceAreas: ["Gulfport", "Biloxi", "Ocean Springs", "Pass Christian"],
    facebookPageUrl: "https://facebook.com/marcusvancems",
    instagramPageUrl: "https://instagram.com/marcusvance_homes",
    crossPostPreference: "areaAndPrice",
    priceRangeMin: 300000,
    priceRangeMax: 1200000,
  },
  {
    id: "agent-3",
    name: "Elena Rostova",
    email: "elena.rostova@cresentsothebys.com",
    phone: "(251) 555-0188",
    officeState: "AL",
    serviceAreas: ["Mobile", "Daphne", "Fairhope", "Spanish Fort"],
    facebookPageUrl: "https://facebook.com/elenarostovaluxury",
    instagramPageUrl: "https://instagram.com/elena_coastal_realty",
    crossPostPreference: "byRequest",
  },
  {
    id: "agent-4",
    name: "David Miller",
    email: "david.miller@cresentsothebys.com",
    phone: "(985) 555-0129",
    officeState: "LA",
    serviceAreas: ["Covington", "Mandeville", "Madisonville", "Bush"],
    facebookPageUrl: "https://facebook.com/davidmillernorthshore",
    instagramPageUrl: "https://instagram.com/davidmiller_realestate",
    crossPostPreference: "areaAndPrice",
    priceRangeMin: 200000,
    priceRangeMax: 650000,
  },
  {
    id: "agent-5",
    name: "Amanda Hayes",
    email: "amanda.hayes@cresentsothebys.com",
    phone: "(504) 555-0177",
    officeState: "LA",
    serviceAreas: ["New Orleans", "Gretna", "Marrero"],
    facebookPageUrl: "https://facebook.com/amandahayeshomes",
    crossPostPreference: "never",
  },
  {
    id: "agent-6",
    name: "Robert Sterling",
    email: "robert.sterling@cresentsothebys.com",
    phone: "(251) 555-0199",
    officeState: "AL",
    serviceAreas: ["Orange Beach", "Gulf Shores", "Foley", "Mobile"],
    facebookPageUrl: "https://facebook.com/robertsterlingal",
    instagramPageUrl: "https://instagram.com/sterling_coastal",
    crossPostPreference: "all",
  },
  {
    id: "agent-7",
    name: "Claire DuBois",
    email: "claire.dubois@cresentsothebys.com",
    phone: "(228) 555-0162",
    officeState: "MS",
    serviceAreas: ["Bay St. Louis", "Waveland", "Pass Christian", "Gulfport"],
    facebookPageUrl: "https://facebook.com/claireduboisrealty",
    instagramPageUrl: "https://instagram.com/claire_coastal_living",
    crossPostPreference: "areaAndPrice",
    priceRangeMin: 450000,
    priceRangeMax: 2500000,
  },
  {
    id: "agent-8",
    name: "Jason Thorne",
    email: "jason.thorne@cresentsothebys.com",
    phone: "(985) 555-0111",
    officeState: "LA",
    serviceAreas: ["Hammond", "Ponchatoula", "Covington", "Bush"],
    facebookPageUrl: "https://facebook.com/jasonthornegroup",
    crossPostPreference: "areaAndPrice",
    priceRangeMin: 150000,
    priceRangeMax: 400000,
  },
];
