import { User } from "@real-estate/types";

export const MOCK_USERS: User[] = [
  {
    id: "usr-001",
    name: "Eleanor Vance (Super Admin)",
    email: "admin@cresentsothebys.com",
    accountType: "superAdmin",
    permissions: [
      "listings:create",
      "listings:edit",
      "listings:delete",
      "discrepancies:resolve",
      "agents:create",
      "agents:edit",
      "agents:delete",
      "socialMatcher:use",
      "users:create",
      "users:edit",
    ],
    createdAt: "2025-01-01T00:00:00.000Z",
    lastLoginAt: "2026-08-13T10:00:00.000Z",
  },
  {
    id: "usr-002",
    name: "Marcus Brody (Listings Staff)",
    email: "listings@cresentsothebys.com",
    accountType: "employee",
    permissions: [
      "listings:create",
      "listings:edit",
      "discrepancies:resolve",
    ],
    createdAt: "2025-02-15T00:00:00.000Z",
    lastLoginAt: "2026-08-12T14:30:00.000Z",
  },
  {
    id: "usr-003",
    name: "Sophia Martinez (Social Matcher)",
    email: "social@cresentsothebys.com",
    accountType: "employee",
    permissions: [
      "socialMatcher:use",
    ],
    createdAt: "2025-03-10T00:00:00.000Z",
    lastLoginAt: "2026-08-11T09:15:00.000Z",
  },
  {
    id: "usr-004",
    name: "David Sterling (Agent Manager)",
    email: "agents@cresentsothebys.com",
    accountType: "employee",
    permissions: [
      "agents:create",
      "agents:edit",
      "agents:delete",
    ],
    createdAt: "2025-04-05T00:00:00.000Z",
    lastLoginAt: "2026-08-10T16:45:00.000Z",
  },
  {
    id: "usr-005",
    name: "Clara Oswald (Full Employee)",
    email: "employee@cresentsothebys.com",
    accountType: "employee",
    permissions: [
      "listings:create",
      "listings:edit",
      "listings:delete",
      "discrepancies:resolve",
      "agents:create",
      "agents:edit",
      "socialMatcher:use",
    ],
    createdAt: "2025-05-20T00:00:00.000Z",
    lastLoginAt: "2026-08-13T08:20:00.000Z",
  },
  {
    id: "usr-006",
    name: "Hannah Abbott (HR Manager)",
    email: "hr@cresentsothebys.com",
    accountType: "employee",
    permissions: [
      "users:create",
      "users:edit",
    ],
    createdAt: "2025-06-01T00:00:00.000Z",
    lastLoginAt: "2026-08-09T11:00:00.000Z",
  },
];
