import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

const LISTINGS_DATA = [
  {
    mlsNumber: "2573656",
    street: "1201 Canal Street Unit 251",
    city: "New Orleans",
    state: "LA",
    zip: "70112",
    price: 259000,
    beds: 2,
    fullBaths: 1,
    halfBaths: 0,
    buildingAreaSqft: 1000,
    lotSizeAcres: 0.01,
    propertyType: "ResidentialCondominium",
    listingType: "Residential Sales",
    status: "active",
    description: "Experience luxury downtown living at its best in this distinctive 2-bedroom, 1-bath condominium in the historic Krauss Building.",
    agentEmail: "liz.baer@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "2573263",
    street: "800 LA-1085",
    city: "Madisonville",
    state: "LA",
    zip: "70447",
    price: 150000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1337,
    lotSizeAcres: 0.3,
    propertyType: "ResidentialMobile/Manufactured Home",
    listingType: "Residential Sales",
    status: "active",
    description: "Calling all investors, renovators, and buyers looking for an opportunity in the Madisonville area!",
    agentEmail: "ronnie.ranatza@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "2573641",
    street: "104 Park Place",
    city: "Covington",
    state: "LA",
    zip: "70433",
    price: 495000,
    beds: 4,
    fullBaths: 3,
    halfBaths: 0,
    buildingAreaSqft: 2600,
    lotSizeAcres: 0.25,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Charming home located in Park Place subdivision of Covington.",
    agentEmail: "puddy.robinson@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "2573643",
    street: "47343 Happywoods Road",
    city: "Hammond",
    state: "LA",
    zip: "70401",
    price: 320000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1950,
    lotSizeAcres: 0.5,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Spacious country living just minutes from downtown Hammond.",
    agentEmail: "katie.huguet@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "4140733",
    street: "847 Royal St",
    city: "Pass Christian",
    state: "MS",
    zip: "39571",
    price: 575000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 1,
    buildingAreaSqft: 2200,
    lotSizeAcres: 0.2,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Beautiful coastal cottage located in the heart of Pass Christian.",
    agentEmail: "lesley.troncoso@cresentsothebys.com",
    officeId: "off-ms-01",
  },
  {
    mlsNumber: "391807",
    street: "25802 Perdido Beach Blvd Unit 903",
    city: "Orange Beach",
    state: "AL",
    zip: "36561",
    price: 789000,
    beds: 2,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1250,
    lotSizeAcres: 0.01,
    propertyType: "Condominium",
    listingType: "Residential Sales",
    status: "active",
    description: "Stunning direct gulf-front condo in prime Orange Beach location.",
    agentEmail: "sandy.davenport@cresentsothebys.com",
    officeId: "off-al-01",
  },
  {
    mlsNumber: "2573549",
    street: "1937 Gentilly Blvd",
    city: "New Orleans",
    state: "LA",
    zip: "70122",
    price: 349000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1650,
    lotSizeAcres: 0.12,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Classic New Orleans home in the historic Gentilly neighborhood.",
    agentEmail: "amanda.mitternight@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "4140506",
    street: "16187 Saucier Lizana Rd",
    city: "Saucier",
    state: "MS",
    zip: "39574",
    price: 285000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1800,
    lotSizeAcres: 2.5,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Quiet country retreat with acreage and serene natural surroundings.",
    agentEmail: "holly.gibbs@cresentsothebys.com",
    officeId: "off-ms-01",
  },
  {
    mlsNumber: "2573489",
    street: "4005 Houma Blvd",
    city: "Metairie",
    state: "LA",
    zip: "70006",
    price: 415000,
    beds: 4,
    fullBaths: 2,
    halfBaths: 1,
    buildingAreaSqft: 2400,
    lotSizeAcres: 0.18,
    propertyType: "Single Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Desirable Metairie location close to medical centers and shopping.",
    agentEmail: "rachel.ringen@cresentsothebys.com",
    officeId: "off-la-01",
  },
  {
    mlsNumber: "2573479",
    street: "5522-24 Laurel Street",
    city: "New Orleans",
    state: "LA",
    zip: "70115",
    price: 699000,
    beds: 4,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 2300,
    lotSizeAcres: 0.08,
    propertyType: "Multi-Family",
    listingType: "Residential Sales",
    status: "active",
    description: "Uptown New Orleans double near Magazine Street corridor.",
    agentEmail: "suzanne.lamore@cresentsothebys.com",
    officeId: "off-la-01",
  },
];

async function seedListings() {
  console.log("🌱 Seeding 10 Real Estate Listings from your dataset...");

  for (const item of LISTINGS_DATA) {
    const agent = await prisma.agent.findUnique({ where: { email: item.agentEmail } });
    if (!agent) {
      console.warn(`Agent ${item.agentEmail} not found, skipping listing ${item.mlsNumber}`);
      continue;
    }

    await prisma.listing.upsert({
      where: { mlsNumber: item.mlsNumber },
      update: {
        street: item.street,
        city: item.city,
        state: item.state,
        zip: item.zip,
        price: new Prisma.Decimal(item.price),
        beds: item.beds,
        fullBaths: item.fullBaths,
        halfBaths: item.halfBaths,
        buildingAreaSqft: new Prisma.Decimal(item.buildingAreaSqft),
        lotSizeAcres: new Prisma.Decimal(item.lotSizeAcres),
        propertyType: item.propertyType,
        listingType: item.listingType,
        status: item.status as any,
        description: item.description,
        listingAgentId: agent.id,
        listingOfficeId: item.officeId,
      },
      create: {
        mlsNumber: item.mlsNumber,
        street: item.street,
        city: item.city,
        state: item.state,
        zip: item.zip,
        price: new Prisma.Decimal(item.price),
        beds: item.beds,
        fullBaths: item.fullBaths,
        halfBaths: item.halfBaths,
        buildingAreaSqft: new Prisma.Decimal(item.buildingAreaSqft),
        lotSizeAcres: new Prisma.Decimal(item.lotSizeAcres),
        propertyType: item.propertyType,
        listingType: item.listingType,
        status: item.status as any,
        description: item.description,
        listDate: new Date(),
        expirationDate: new Date(Date.now() + 180 * 86400000),
        listingAgentId: agent.id,
        listingOfficeId: item.officeId,
      },
    });
  }

  console.log("✓ Listings seeded successfully!");
}

seedListings()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
