import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient();

export const SOURCE_OF_TRUTH_LISTINGS = [
  {
    mlsNumber: "2573656",
    street: "1201 Canal Street Unit 251",
    city: "New Orleans",
    state: "LA",
    zip: "70112",
    price: 259000,
    beds: 2,
    fullBaths: 1,
    halfBaths: 0,
    buildingAreaSqft: 1000,
    lotSizeAcres: 0.01,
    propertyType: "ResidentialCondominium",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Experience luxury downtown living at its best in this distinctive 2-bedroom, 1-bath condominium in the historic Krauss Building, formerly Krauss Department Store—one of New Orleans’ leading department stores for more than 90 years before its conversion into luxury residences in 2009. The light-filled interior features soaring 16-foot ceilings, beautiful wood floors, granite countertops and striking architectural character. Recent improvements include a new washer and dryer and a new water heater.\nResidents enjoy exceptional amenities, including a rooftop saltwater pool with sweeping city views, fitness center, sauna, meeting rooms, 24-hour security, valet parking and a dedicated parking space. Centrally located on Canal Street at the edge of the French Quarter, this prized address is next to the iconic Saenger and Joy Theaters and just blocks from the medical corridor, including Tulane Medical Center, LSU Health Sciences Center and the VA Medical Center. Historic New Orleans character, modern amenities and an unbeatable downtown location!",
    agentEmail: "liz.baer@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a87760f18408e775cda44bf/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2573263",
    street: "800 LA-1085",
    city: "Madisonville",
    state: "LA",
    zip: "70447",
    price: 150000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1337,
    lotSizeAcres: 0.3,
    propertyType: "ResidentialMobile/Manufactured Home",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Calling all investors, renovators, and buyers looking for an opportunity in the Madisonville area! This 3 bedroom, 2 bath home sits on a spacious corner lot of just over 1/3 acre along the desirable Highway 1085 corridor. The property features a large fenced yard, mature trees, and a detached garage offering plenty of room for storage, a workshop, or your next project. The location is the real standout. Enjoy the space and flexibility of a larger homesite while remaining convenient to Madisonville, Covington, Mandeville, shopping, dining, recreation, and major Northshore thoroughfares. The area is also served by sought after Madisonville area public schools. The home offers plenty of potential for an investor, renovation project, rental property, or buyer ready to bring their own vision. With a great lot, useful outbuilding, convenient location, and room to add value, there is plenty of opportunity here. Bring your ideas and make it your own! Call today to schedule a private showing.",
    agentEmail: "ronnie.ranatza@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a5fc7aa587d729446af7a6a/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2565907",
    street: "74438 Holly Lane",
    city: "Covington",
    state: "LA",
    zip: "70435",
    price: 850000,
    beds: 3,
    fullBaths: 3,
    halfBaths: 0,
    buildingAreaSqft: 3243,
    lotSizeAcres: 2.44,
    propertyType: "ResidentialSingle Family Detached",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Nestled among mature oaks and pines on 2.4 private, wooded acres just 10 minutes from town, this exceptional custom-designed 3-bedroom home combines architectural character with everyday livability. The exterior showcases real stucco with striking gable rooflines and a durable standing seam metal roof, while 6\" exterior walls with blown-in insulation deliver energy efficiency you can feel. Multiple sets of French doors — framed in rich black trim — open onto the wooded lot, and a custom iron-railed balcony off the second floor adds old-world charm. Step inside to soaring high ceilings and an open-concept layout where the great room flows seamlessly into a chef's kitchen built for entertaining. Rich engineered hardwood flooring runs throughout the main level, paired with dark custom cabinetry, dramatic marble countertops, a large farmhouse sink, a sleek induction stovetop, a striking stainless hood, and a pot filler. A generous island with bar seating anchors the open kitchen, complemented by a designer tile backsplash and abundant natural light from oversized windows throughout. Upstairs, real wood flooring warms the living areas. A striking staircase with wrought iron balusters leads to the upper level, where a huge bonus/flex room with vaulted ceilings and rich blue-gray walls offers endless possibilities — media room, playroom, or home gym — plus a walk-in attic for exceptional additional storage. The primary suite delivers a true spa experience with a rain head and body spray shower system. Practical luxury continues with a large gun safe, two separate A/C systems for zoned comfort, and a whole-home water filtration system. Set back from the road with a wooded, private setting yet just minutes from everything Covington has to offer, this meticulously crafted home is a rare find. Schedule your private showing today.",
    agentEmail: "puddy.robinson@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a4d58d1bb2449f93730ff71/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2573655",
    street: "13092 East Coles Creek Loop",
    city: "Hammond",
    state: "LA",
    zip: "70403",
    price: 360000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1752,
    lotSizeAcres: 0.26,
    propertyType: "ResidentialSingle Family Detached",
    listingType: "Residential Sales",
    status: "active",
    description:
      "This French Country inspired home has been exceptionally well maintained and thoughtfully updated, complete with a 420 sq ft detached guest suite. As you arrive, you will notice the beautifully maintained landscaping, well cared for yard and extra touches that make this property exceptional. An additional parking pad provides convenient parking for the detached guest suite, which has its own private entry. As you enter, you are greeted by a formal foyer that opens to the living room. The living room showcases a custom brick gas burning fireplace, double crown molding and lots of windows that fill the space with natural light. Just off the living room, the kitchen has been updated with a new center island, granite countertops, new stainless steel appliances, plenty of cabinetry and a generous amount of counter space for cooking or entertaining. A spacious primary suite features a vaulted tray ceiling and private ensuite with a double vanity, walk in closet, separate shower and hydro tub. Both additional bedrooms offer generous space and would work well for family, guests or a dedicated office. Out back, enjoy the covered screened in patio overlooking the fully fenced backyard. Subsurface drainage runs throughout the property, helping keep the yard in great shape. There is plenty of room to spread out, garden, entertain and enjoy the outdoors, with easy access to the detached guest suite. The detached guest suite offers its own living room with luxury vinyl plank flooring, a kitchen with stainless steel appliances and granite countertops, one bedroom and a private bath. A front porch and separate entry give the space privacy, while a walking path provides access to the main home and driveway. You will also notice gutters, two storage sheds, including a newer shed large enough to accommodate a golf cart, and a 20 KW whole house generator. The garage has been set up with an entertaining bar area and a retractable screen with a door, making it a great spot to enjoy the space while keeping out those hot Louisiana mosquitoes and bugs. This property has been thoughtfully cared for inside and out, with the space, updates and extras that make everyday living easy and enjoyable. With all of the thoughtful updates, extra space and amenities this property offers, this is a property you will want to see in person.",
    agentEmail: "katie.huguet@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a8876db18408e775cdb0eeb/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "4159867",
    street: "132 Vista Drive",
    city: "Pass Christian",
    state: "MS",
    zip: "39571",
    price: 85000,
    beds: 0,
    fullBaths: 0,
    halfBaths: 0,
    buildingAreaSqft: 0,
    lotSizeAcres: 0.19,
    propertyType: "ResidentialResidential Lot",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Build your dream home and embrace the coastal lifestyle on this spacious, cleared lot in the Beach Vista community of Pass Christian. The homesite offers a wonderful blank canvas for creating a primary residence or relaxing weekend retreat on the Mississippi Gulf Coast. Enjoy access to the community pool included in your HOA fees, take a short stroll to the beach, or hop on your golf cart for a ride to Downtown Pass Christian, where you'll find local restaurants, shops, entertainment, and the harbor. Bring your house plans and discover the possibilities this well-located property has to offer!",
    agentEmail: "lesley.troncoso@cresentsothebys.com",
    officeId: "off-ms-01",
    mlsSource: "MLS United",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a887ac418408e775cdb1acc/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "409364",
    street: "23008 Perdido Beach Blvd 606 Unit# 606",
    city: "Orange Beach",
    state: "AL",
    zip: "36561",
    price: 1245000,
    beds: 2,
    fullBaths: 3,
    halfBaths: 0,
    buildingAreaSqft: 1549,
    lotSizeAcres: 0,
    propertyType: "ResidentialOther Residential",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Beautiful NEW beachfront condo. This fabulous condominium offers generous living space featuring a very spacious, open floor plan. Absolutely gorgeous views through the floor to ceiling glass windows and doors, and plenty of it in the extra-large living space. Fine, coastal design with fabulous upgrades including a built-in fireplace, Quartz countertops, counter-height bar, modern hood vent over stove, bar-front tile, upgraded paint throughout, upgraded tile on kitchen back splash, tiled backsplash on wet bar, and upgraded cabinets-over $20,000 in upgrades. The high ceilings and floor-to-ceiling glass provide breathtaking views of the Gulf and beautiful beaches of Orange Beach. The kitchen has upgraded custom cabinets, upgraded, tiled counter-height bar, stainless steel appliances, a tiled backsplash, and granite countertops. Enjoy the grand amenities including a gulf-front lazy river, outdoor pool, indoor pool, splash pad, hot tub and a grilling area. Investors will appreciate the strong rental income potential of this property, making it not only a luxurious residential choice but also a smart investment opportunity. Embrace the beachfront lifestyle you've dreamed of! Buyer to verify all information during due diligence.",
    agentEmail: "sandy.davenport@cresentsothebys.com",
    officeId: "off-al-01",
    mlsSource: "Baldwin County Association of Realtors",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a88c7ec31dc41b872ef161e/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2571857",
    street: "2441-43 Gladiolus Street",
    city: "New Orleans",
    state: "LA",
    zip: "70122",
    price: 364000,
    beds: 7,
    fullBaths: 3,
    halfBaths: 0,
    buildingAreaSqft: 2800,
    lotSizeAcres: 0,
    propertyType: "ResidentialDuplex",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Spacious Multifamily in Prime Gentilly Location! Located in a sought-after Gentilly neighborhood, this impressive two-story multifamily property offers 2,800 sq ft of living space and an excellent investment opportunity. The downstairs unit features 3 bedrooms and 1 bath, while the upstairs unit has 4 bedrooms and 2 bath – allowing maximum rental income. Currently generating $38,100 in annual rents, this property is a strong income producer. Upgrades include a new roof (2022), granite countertops, all ceramic tile floors, and a new privacy fence. Both units enjoy central air and heat, and the home sits in an X flood zone for added peace of mind. With its great location, modern updates, and generous size, this property would work for investors or owner-occupants looking to live in one unit while renting the other.",
    agentEmail: "amanda.mitternight@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a809192097dc8f11367feca/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "407058",
    street: "455 East Beach Boulevard Unit 1813",
    city: "Gulf Shores",
    state: "AL",
    zip: "36542",
    price: 715000,
    beds: 2,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1161,
    lotSizeAcres: 0,
    propertyType: "ResidentialCondominium",
    listingType: "Residential Sales",
    status: "pending",
    description:
      "Corner unit with wrap balcony! Rare and utterly unique, this 2-bedroom corner unit with a bunk room condominium at Lighthouse offers a Gulf-front experience unlike other two-bedroom units. Direct views of the Gulf and a west-facing wrap balcony that captures amazing sunsets. Soothing coastal interiors blend with calming decor and tasteful finishes throughout. The kitchen has a beautiful tile backsplash, and a tile surround on the bar blends perfectly. A dedicated BUNK ROOM maximizes sleeping space, making this a fantastic vacation rental. New luxury vinyl flooring, new paint, and a beautifully remodeled primary bathroom with a spacious, tiled walk-in shower and gorgeous granite counters are just some of the upgrades in this fabulous condo. Lighthouse is known for its grand amenities, including a large outdoor pool with an ample deck, an indoor pool, a fitness center, and a grilling area. On-site management and the building's strong reputation add lasting peace of mind and genuine investment appeal.\nThe location is one of the best. Stroll to Gulf State Park Pier for fishing and scenic walks, or head to The Hangout for live music, dining, and family fun just moments away. Whether you seek a personal beach escape or a proven income producer, this exceptional corner retreat delivers. Schedule your private showing today and claim your place on the sand. Buyer to verify all information during due diligence.",
    agentEmail: "sandy.davenport@cresentsothebys.com",
    officeId: "off-al-01",
    mlsSource: "Baldwin Realtors",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a7a7375b327a7101471aa2b/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "4158391",
    street: "19505 Wallace Way",
    city: "Saucier",
    state: "MS",
    zip: "39574",
    price: 229900,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1459,
    lotSizeAcres: 0,
    propertyType: "ResidentialSingle Family Detached",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Whether you're purchasing your first home or looking for more space for a growing family, this **3-bedroom, 2-bath home** offers incredible potential in a desirable Saucier location. With solid bones and room to make it your own, this fixer-upper is the perfect opportunity to build equity while creating a home that reflects your style. Situated in an area served by **top-rated schools**, the property provides the peaceful setting of country living while remaining convenient to shopping, dining, and the Mississippi Gulf Coast. Bring your vision and transform this home into the one you've always wanted. **Property Highlights** * 3 Bedrooms | 2 Bathrooms *** NEW ROOF * NEW stove, NEW water heater, and NEW above-stove microwave*** Great opportunity for first-time buyers or investors * Ideal for a growing family * Excellent renovation potential (needs minimal repairs)",
    agentEmail: "holly.gibbs@cresentsothebys.com",
    officeId: "off-ms-01",
    mlsSource: "MLS United",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a74cdb8d4eb017409adfbf9/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2571943",
    street: "6009 Rosalie Court",
    city: "Metairie",
    state: "LA",
    zip: "70003",
    price: 290000,
    beds: 3,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 1501,
    lotSizeAcres: 0.14,
    propertyType: "ResidentialSingle Family Detached",
    listingType: "Residential Sales",
    status: "pending",
    description:
      "Beautifully updated home in the heart of Metairie just two blocks from Lafreniere Park! This well-maintained property features an updated kitchen with granite countertops and stainless steel appliances, along with newer windows that enhance both efficiency and natural light. The fortified roof, only one year old, offers added durability and peace of mind. The spacious primary suite includes a large walk-in closet and a well-appointed bathroom with dual vanities. Wood-look tile flooring runs throughout the living areas and bedrooms, while tile is featured in the kitchen, foyer, and bathrooms for durability and easy maintenance. You’ll also find abundant closet space and storage options throughout. A standout feature is the oversized man cave, great for entertaining, hobbies, or a private retreat, plus a separate storage shed for even more convenience. Conveniently located by grocery stores, dining, shopping, the interstate, and hospitals, this home truly offers both comfort and accessibility. Located in Flood Zone X! Current flood policy is assumable.",
    agentEmail: "rachel.ringen@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a7b5995097dc8f1132989c2/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2569945",
    street: "729 Lyons Street #A",
    city: "New Orleans",
    state: "LA",
    zip: "70115",
    price: 2200,
    beds: 2,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 792,
    lotSizeAcres: 0.03,
    propertyType: "ResidentialCondominium",
    listingType: "Residential Lease",
    status: "active",
    description:
      "One level, ground floor living just two short blocks to all Magazine Street has to offer, this 2 Bedroom 2 Bath condo on the first floor of a 3-plex is a hidden gem with an open kitchen/dining/living space, tasteful updates including marble kitchen countertops and stainless appliances, and a mudroom PLUS ample storage off the kitchen. Ensuite bath in primary suite, and a separate full guest bath. Water is included in the rent, and Entergy bills average only $68 per month! The large back patio is for the use of this unit and is partially covered and overlooks a lush back garden. Plentiful street parking. One pet considered on case by case basis, up to 40 pounds w/additional deposit.",
    agentEmail: "suzanne.lamore@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a6a7caf90f82b56e24c6bdb/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2565319",
    street: "623 Kerlerec Street",
    city: "New Orleans",
    state: "LA",
    zip: "70116",
    price: 4250,
    beds: 2,
    fullBaths: 2,
    halfBaths: 1,
    buildingAreaSqft: 1380,
    lotSizeAcres: 0.13,
    propertyType: "ResidentialDuplex",
    listingType: "Residential Lease",
    status: "active",
    description:
      "Furnished half double available for 6-12 month terms! $4,250 for 12 months, willing to negotiate for shorter terms. Completely restored Victorian Double in the heart of the vibrant Frenchmen Street scene. With a vibe as sultry as the New Orleans summer, this fully furnished unit features a soothing gray-blue-green color palate, two ensuite bedrooms (one on each floor) with full baths and full-size closets. With high ceilings, original wood floors and an incredible floor plan that includes an eat in kitchen, bar, 1st floor dual function office/laundry room, second floor office/reading loft, storage closets, fenced back yard and a second-floor balcony as well as an inviting front porch, pack your bag and call this one home! The essence of New Orleans is reflected in the thoughtfully curated art collection featuring local artists and mixed media wall hangings as well as the luxurious yet comfortable furnishings. Entertaining is a breeze with the built-in bar adjacent to the chef's kitchen with an oversize island with ample seating, gas range oven and new stainless-steel appliances. High speed internet is included. Smoking is not allowed for this unit. Pets under 20lbs may be accepted with owners' approval on a case by case basis and subject to a non-refundable cleaning fee at end of lease.",
    agentEmail: "dawnne.keeney@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/68960fe6bc03648e59642c84/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2572211",
    street: "11 Tolawa Lane",
    city: "Covington",
    state: "LA",
    zip: "70433",
    price: 1750000,
    beds: 5,
    fullBaths: 3,
    halfBaths: 2,
    buildingAreaSqft: 4618,
    lotSizeAcres: 1.56,
    propertyType: "ResidentialSingle Family Attached",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Refined transitional European estate set on 1.56 acres just minutes from I-12 and the Causeway. Thoughtfully designed with timeless architecture and quiet luxury, this home welcomes you with a circular drive, porte-cochère, and multiple garage spaces, including a golf cart storage garage. Inside, warm hardwood floors and classic millwork frame a chef’s kitchen featuring a 48” range, double ovens, and built-in refrigerator/freezer columns. The primary suite offers a private retreat with dual closets and in-closet laundry hookup. Designed for both everyday living and effortless entertaining with three mudrooms, a service pantry, and a spacious bonus room with future bath potential. The raised terrace with turf and a fully equipped outdoor kitchen creates an ideal setting for gathering. A rare combination of land, location, and craftsmanship on the Northshore.",
    agentEmail: "katie.martin@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a7b799b9fa7f42254e9575c/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2572776",
    street: "TBD Tolawa Lane",
    city: "Covington",
    state: "LA",
    zip: "70433",
    price: 175000,
    beds: 0,
    fullBaths: 0,
    halfBaths: 0,
    buildingAreaSqft: 0,
    lotSizeAcres: 1.62,
    propertyType: "ResidentialResidential Lot",
    listingType: "Residential Sales",
    status: "active",
    description:
      "Tucked away on quiet Tolawa Lane, this future homesite offers a rare sense of privacy while keeping you close to everything Covington has to offer. Surrounded by a peaceful, tucked-away setting, it feels removed from the everyday hustle yet is conveniently located near Lakeview Hospital with easy access to I-12 and the Causeway. An ideal opportunity to build your dream home with room to spread out, without sacrificing convenience. Property may also be purchased in conjunction with 11 Tolawa Lane with an acceptable offer.",
    agentEmail: "katie.martin@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a83eb59097dc8f1138f0c5b/mediabrowser/photogallery"],
  },
  {
    mlsNumber: "2568606",
    street: "41325 Crown Drive Extension",
    city: "Ponchatoula",
    state: "LA",
    zip: "70454",
    price: 349000,
    beds: 4,
    fullBaths: 2,
    halfBaths: 0,
    buildingAreaSqft: 2384,
    lotSizeAcres: 9.08,
    propertyType: "ResidentialSingle Family Detached",
    listingType: "Residential Sales",
    status: "pending",
    description:
      "Yes...9.08 Acres, Loads of Outdoor Building Storage.Large den with Cathedral Ceiling, Open Bar with Brick-Wood burning fire place.Formal Dinning Room and Sunken Sitting Room with a walk in foyer, This home features 4 bedrooms 2 baths. also feature a 20x28 sun room. Relax on a covered front porch. 30x20 Workshop plus a 16x10 Storage Building. Four Acres of cleared and 5 acres Wooded on a Dead-End Street. Get Ready to Hunt and Garden.A rare opportunity awaits for you.",
    agentEmail: "tuesday.edwards@cresentsothebys.com",
    officeId: "off-la-01",
    mlsSource: "NOMAR MLS",
    photos: ["https://crescentsir.connect.brokerageengine.com/listing/6a627407587d729446b57ae6/mediabrowser/photogallery"],
  },
];

async function seedSourceOfTruth() {
  console.log("🌱 Ingesting 15 Source of Truth Listings...");

  for (const item of SOURCE_OF_TRUTH_LISTINGS) {
    const agent = await prisma.agent.findUnique({ where: { email: item.agentEmail } });
    if (!agent) {
      console.warn(`⚠️ Agent not found for ${item.agentEmail}, skipping ${item.mlsNumber}`);
      continue;
    }

    await prisma.listing.upsert({
      where: { mlsNumber: item.mlsNumber },
      update: {
        street: item.street,
        city: item.city,
        state: item.state,
        zip: item.zip,
        price: new Prisma.Decimal(item.price),
        beds: item.beds,
        fullBaths: item.fullBaths,
        halfBaths: item.halfBaths,
        buildingAreaSqft: new Prisma.Decimal(item.buildingAreaSqft),
        lotSizeAcres: new Prisma.Decimal(item.lotSizeAcres),
        propertyType: item.propertyType,
        propertyStyle: item.propertyType || "Traditional",
        listingType: item.listingType,
        status: (item.status as any) || "active",
        description: item.description,
        legalDescription: "Official recorded parcel & legal plat on file",
        mlsSource: item.mlsSource,
        listingAgentId: agent.id,
        listingOfficeId: item.officeId,
      },
      create: {
        mlsNumber: item.mlsNumber,
        street: item.street,
        city: item.city,
        state: item.state,
        zip: item.zip,
        price: new Prisma.Decimal(item.price),
        beds: item.beds,
        fullBaths: item.fullBaths,
        halfBaths: item.halfBaths,
        buildingAreaSqft: new Prisma.Decimal(item.buildingAreaSqft),
        lotSizeAcres: new Prisma.Decimal(item.lotSizeAcres),
        propertyType: item.propertyType,
        propertyStyle: item.propertyType || "Traditional",
        listingType: item.listingType,
        status: (item.status as any) || "active",
        description: item.description,
        legalDescription: "Official recorded parcel & legal plat on file",
        mlsSource: item.mlsSource,
        listDate: new Date(),
        expirationDate: new Date(Date.now() + 180 * 86400000),
        listingAgentId: agent.id,
        listingOfficeId: item.officeId,
        photos: {
          create: item.photos.map((url, idx) => ({
            url,
            position: idx + 1,
            source: "client",
          })),
        },
      },
    });
  }

  console.log(`✅ Successfully seeded ${SOURCE_OF_TRUTH_LISTINGS.length} Source of Truth listings.`);
}

seedSourceOfTruth()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
